services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0 #
    container_name: mealie
    restart: always
    networks:
    - t3_proxy
    ports:
    - "9925:9000" #
    secrets:
    - openai_mealie_key
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
    - ${APPDIR}/mealie:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: $TZ
      BASE_URL: https://mealie.${DOMAINNAME_1}:9925
      OPENAI_API_KEY_FILE: /run/secrets/openai_mealie_key
      OPENAI_ENABLE_IMAGE_SERVICES: true
    labels:
    - "traefik.enable=true"
    # HTTP Routers
    - "traefik.http.routers.mealie-rtr.entrypoints=websecure"
    - "traefik.http.routers.mealie-rtr.rule=Host(`mealie.$DOMAINNAME_1`)"
    # Middlewares
    # - "traefik.http.routers.plex-rtr.middlewares=chain-no-auth@file"
    # HTTP Services
    - "traefik.http.routers.mealie-rtr.service=mealie-svc"
    - "traefik.http.services.mealie-svc.loadbalancer.server.port=9000"
