services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      LOG_LEVEL: debug
      TZ: $TZ
    ports:
    - 5055:5055
    volumes:
    - $DOCKERDIR/appdata/overseerr:/app/config
    - $LOGDIR/overseer:/app/config/logs
    networks:
    - default
    - socket_proxy
    - t3_proxy
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    # HTTP Routers
    - "traefik.http.routers.overseerr-rtr.entrypoints=websecure"
    - "traefik.http.routers.overseerr-rtr.rule=Host(`request.$DOMAINNAME_1`)"
    # Middlewares
    - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
    - "traefik.http.routers.overseerr-rtr.middlewares=chain-no-auth@file"
    # HTTP Services
    - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
