services:
  threadfin:
    image: fyb3roptik/threadfin
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=$TZ
    volumes:
      - $APPDIR/threadfin/conf:/home/threadfin/conf
      - $APPDIR/threadfin/temp:/tmp/threadfin:rw
    restart: unless-stopped
