services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    labels:
    - "traefik.enable=true"
    # HTTP Routers
    - "traefik.http.routers.wizarr-rtr.entrypoints=websecure"
    - "traefik.http.routers.wizarr-rtr.rule=Host(`invite.$DOMAINNAME_1`)"
    # Middlewares
    - "traefik.http.routers.wizarr-rtr.service=wizarr-svc"
    # HTTP Services
    - "traefik.http.services.wizarr-svc.loadbalancer.server.port=5690"
    networks:
    - socket_proxy
    - t3_proxy
    ports:
    - 5690:5690
    volumes:
    - $APPDIR/wizarr/database:/data/database
