services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: always
    networks:
      crowdsec:
    ports:
    - 13222:8080
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      COLLECTIONS: "crowdsecurity/nginx"
    depends_on:
    - 'traefik'
    volumes:
    ## Bad pratice to mount docker socket into a container
    #- /var/run/docker.sock:/var/run/docker.sock:ro
    ######################################################
    #- $APPDIR/crowdsecconfig/acquis.yaml:/etc/crowdsec/acquis.yaml
    #- $APPDIR/crowdsecdb:/var/lib/crowdsec/data/
    #- $APPDIR/crowdsec:/etc/crowdsec/
    - $DOCKERDIR/appdata/crowdsec/data:/var/lib/crowdsec/data
    - $DOCKERDIR/appdata/crowdsec/config:/etc/crowdsec
    - /var/log:/var/log:ro
    - $DOCKERDIR/logs/homeserver:/logs/web
