services:
  dbgate:
    image: dbgate/dbgate-premium
    restart: always
    secrets:
    - dbgate_password
    - mariadb_root_password
    ports:
    - 7492:3000
    networks:
    - socket_proxy
    environment:
      STORAGE_SERVER: mariadb
      STORAGE_USER: root
      # STORAGE_KEY_FILE_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      STORAGE_PORT: 3306
      STORAGE_DATABASE: dbgate
      STORAGE_ENGINE: mysql@dbgate-plugin-mysql
      # ADMIN_PASSWORD_FILE: ${DBGATE_PASSWORD}
