services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: $PUID:$PGID
    networks:
    - logging_backend
    ports:
    - '9095:3000'
    depends_on:
    - prometheus
    volumes:
    - logs:/var/log
    - $APPDIR/grafana:/var/lib/grafana

volumes:
  logs:
