services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: $PUID:$PGID
    networks:
    - socket_proxy
    ports:
    - '3002:3000'
    depends_on:
    - prometheus
    volumes:
    - $LOGDIR/grafana:/var/log
    - $APPDIR/grafana:/var/lib/grafana
