services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    user: $PUID:$PGID
    networks:
    - logging_backend
    ports:
    - "9094:3100"
    volumes:
    - $APPDIR/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    - logs:/var/log
    command: -config.file=/etc/loki/loki-config.yaml

volumes:
  logs:
