---
services:
  prometheus:
    image: prom/prometheus
    container_name: prom
    ports:
    - 9096:9090
    networks:
    #- socket_proxy
    - default
    volumes:
    - $APPDIR/prometheus:/etc/prometheus
    - $LOGDIR/prometheus:/var/log
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    restart: always
