---
services:
  prometheus:
    image: prom/prometheus
    container_name: prom
    ports:
    - 9096:9090
    networks:
    - logging_backend
    volumes:
    - $APPDIR/prometheus:/etc/prometheus
    - logs:/var/log
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    restart: always

volumes:
  logs:
