services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
    - $APPDIR/:/var/log
    - $LOGDIR/:/var/log2
    - $APPDIR/promtail:/etc/promtail
    command:
    - -config.file=/etc/promtail/config.yml
    - -config.expand-env=true
    ports:
    - 9080:9080
    - 31022:31022
    networks:
    - socket_proxy
