services:
  syslog-ng:
    container_name: syslog
    environment:
    - PUID=1001
    - PGID=1001
    - TZ=America/Chicago
    - LOG_TO_STDOUT=false
    image: lscr.io/linuxserver/syslog-ng:latest
    ports:
    - 514:5514/udp
    - 601:6601/tcp
    - 6514:6514/tcp
    restart: unless-stopped
    volumes:
    - $APPDIR/syslog:/config
    - $APPDIR/:/var/syslog:ro
    - /var/log:/var/syslog:ro
