services:
  socket-proxy:
    container_name: socket-proxy
    environment:
    - LOG_LEVEL=info
    - EVENTS=1
    - PING=1
    - VERSION=1
    - AUTH=0
    - SECRETS=0
    - POST=1
    - BUILD=0
    - COMMIT=0
    - CONFIGS=0
    - CONTAINERS=1
    - DISTRIBUTION=0
    - EXEC=0
    - IMAGES=1
    - INFO=1
    - NETWORKS=1
    - NODES=0
    - PLUGINS=0
    - SERVICES=1
    - SESSION=0
    - SWARM=0
    - SYSTEM=0
    - TASKS=1
    - VOLUMES=1
    image: tecnativa/docker-socket-proxy
    networks:
      socket_proxy:
        ipv4_address: 192.168.51.254
    privileged: true
    ports:
    - "127.0.0.1:2375:2375"
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - $LOGDIR/socket_proxy:/var/log
