services:
  whoami:
    container_name: whoami
    depends_on:
    - traefik
    environment:
    - TZ=$TZ
    image: traefik/whoami:latest
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami-rtr.entrypoints=websecure"
    - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.$DOMAINNAME_1`)"
    - "traefik.http.routers.whoami-rtr.middlewares=crowdsec-bouncer@file"
    - "traefik.http.routers.whoami-rtr.service=whoami-svc"
    - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"
    networks:
    - t3_proxy
    restart: unless-stopped
    security_opt:
    - no-new-privileges=true
