services:
  bazarr_anime:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr_anime
    environment:
    - PUID=1001
    - PGID=1001
    - TZ=$TZ
    volumes:
    - $APPDIR/bazarr_anime:/config
    - $DATADIR/anime:/data/anime
    ports:
    - 5644:6767
    restart: unless-stopped
