services:
  tautulli:
    container_name: tautulli
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    image: lscr.io/linuxserver/tautulli:latest
    networks:
    - socket_proxy
    ports:
    - "8181:8181"
    restart: "no"
    security_opt:
    - no-new-privileges:true
    volumes:
    - $DOCKERDIR/appdata/tautulli/config:/config
    - $DOCKERDIR/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
