services:
  sabnzbd:
    container_name: sabnzbd
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 2
    image: lscr.io/linuxserver/sabnzbd:latest
    networks:
    - media_backend
    ports:
    - "8084:8080"
    restart: unless-stopped
    read_only: false
    tmpfs:
    - /run:exec
    user: $PUID:$PGID
    volumes:
    - $DOCKERDIR/appdata/sabnzbd:/config
    - $DOWNDIR:/data/downloads
    # - logs:/config/logs
    - $DATADIR/TV/MasterClass:/masterclass
    - $DATADIR/private:/data/private

# volumes:
#   logs:

# Will deploy https://app.crowdsec.net/hub/author/crowdsecurity/log-parsers/sabnzbd-logs soon
