services:
  configarr:
    image: ghcr.io/raydak-labs/configarr:latest
    container_name: configarr
    user: $PUID:$PGID # Optional, defaults to root:root
    environment:
      - TZ=$TZ
    volumes:
      - $APPDIR/configarr/config:/app/config # Contains the config.yml and secrets.yml
      - $APPDIR/configarr/dockerrepos:/app/repos # Cache repositories
      - $APPDIR/configarr/custom/cfs:/app/cfs # Optional if custom formats locally provided
      - $APPDIR/configarr/custom/templates:/app/templates # Optional if custom templates
    # restart: "no" # optional make sure this is set to no or removed. Default is no
