services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    user: $PUID:$PGID
    environment:
      TZ: $TZ
    volumes:
    - $DOCKERDIR/appdata/lidarr:/config
    - $DATADIR/Music:/data/music
    - $DOWNDIR:/data/downloads
    - $LOGDIR/lidarr:/var/log
    ports:
    - 8686:8686
    healthcheck:
      test: curl -f http://localhost:8686/ping || exit 1
      interval: 5m00s
      timeout: 10s
      retries: 2
      start_period: 30s
    restart: unless-stopped
