services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
    - media_backend
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
    - $DOCKERDIR/appdata/prowlar:/config
    - $DOWNDIR:/data/downloads
    user: $PUID:$PGID
    ports:
    - 9696:9696
    healthcheck:
      test: curl -f http://localhost:9696/ping || exit 1
      interval: 5m00s
      timeout: 10s
      retries: 2
      start_period: 30s
    restart: unless-stopped
    # Will deploy https://app.crowdsec.net/hub/author/schiz0phr3ne/log-parsers/prowlarr-logs soon
