services:
  # Radarr - Movie management
  radarr:
    image: ghcr.io/home-operations/radarr:5.21.0.9792
    container_name: radarr
    security_opt:
    - no-new-privileges:true
    restart: "unless-stopped"
    healthcheck:
      test: curl -f http://localhost:7878/ping || exit 1
      interval: 5m00s
      timeout: 10s
      retries: 2
      start_period: 30s
    networks:
    - media_backend
    ports:
    - "7878:7878"
    user: $PUID:$PGID
    volumes:
    - $DOCKERDIR/appdata/radarr:/config
    - $DATADIR/Movies:/data/movies
    - $DOWNDIR:/data/downloads
    - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # Will deploy https://app.crowdsec.net/hub/author/schiz0phr3ne/log-parsers/radarr-logs soon
