services:
  readarr_audio:
    container_name: readarr_audio
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    healthcheck:
      test: curl -f http://localhost:8787/ping || exit 1
      interval: 5m00s
      timeout: 10s
      retries: 2
      start_period: 30s
    image: lscr.io/linuxserver/readarr:develop
    networks:
    - socket_proxy
    ports:
    - 8788:8788
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
    - $DOCKERDIR/appdata/readarr_audio:/config
    #- $DATADIR/books:/data/books
    - $DATADIR/audiobooks:/data/spoken
    - $DOWNDIR:/data/downloads
    - logs:/var/log

volumes:
  logs:
