volumes:
  mysql_data:


services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    networks:
    - socket_proxy
    secrets:
    - mariadb_root_password
    environment:
    - MARIADB_ROOT_PASSWORD_FILE=${MARIADB_ROOT_PASSWORD}
    ports:
    - 3306:3306
    command: --max_allowed_packet=32505856
    volumes:
    - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
